# Maintainer: Chieh

version: '3.8' 
services: 
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_webserver2003
      shm_size: 1gb
    image: (name)/webserver:0.1
    shm_size: 2gb

    ### If you already have, you can use it.
    # image: chiehpower/trtis:2003
    ports:
      - "5000:5000"
    container_name: webserver
    # links:
    #   - tritonserver 

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  tritonserver:
    image: nvcr.io/nvidia/tritonserver:20.03.1-py3
    ports:
      - "8000:8000"
      - "8001:8001" 
      - "8002:8002"  
    volumes:
      - (model_repository path):/models 
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: tritonserver --model-store=/models 
    shm_size: 2gb
    ulimits:
    #   memlock: -1
      stack: 67108864 
    container_name: trt_serving20031

