
############################
# global:
  # resolve_timeout: 2h

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://0.0.0.0:5000/alert/'  #告警webhook地址，告警信息會post到該地址，需要編寫服務
    send_resolved: true

# # 接收該告警數據
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning' #目標告警狀態
#     equal: ['alertname', 'dev', 'instance']